### ISSUE TITLE
Vote database table

### ISSUE THREAD

**Issue by TechnicalParadox** [RaeStichter/paranormal-tourism#6]
## Columns
- 'id' - int, notNull, primaryKey, autoIncrement
- 'user_id' - int, notNull, refs User.id
- 'attraction_id' - int, notNull, refs Attraction.id
- 'weight' - int - -1/+1, notNull, is the vote a thumbs up or down? used to calculate average

**Comment by RaeStichter** [comment]
Nice to have - not for first round.

**Comment by TechnicalParadox** [comment]
Not MVP but I added this model anyway so that we don't have to change the database structure at a later date, functionality can be ignored until we have MVP
